# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('data', models.DateField()),
                ('taxaDesconto', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('n_lugares', models.IntegerField()),
                ('contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=70)),
                ('nome', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious.Utilizador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious.Prato'),
        ),
    ]
